---
name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go lang environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58

      - name: Lint code
        run: golangci-lint run

      - name: Run tests
        run: go test -v ./...
